name: Build and Deploy Code

# on:
#     push:
#         branches:
#             - "main"
#             - "another branch"
#     pull_request:
#         branches:
#             - "main"
#             - "another branch"

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Pulling git repo
              uses: actions/checkout@v4
            - name: say hi to vineet
              run: echo "hello vineet"